const county = [
  {
    CountyID: "A",
    CountyName: "臺北市",
    CountyCode: "63000",
    County: "Taipei",
    CityID: "A",
    Version: "21.08.1",
  },
  {
    CountyID: "B",
    CountyName: "臺中市",
    CountyCode: "66000",
    County: "Taichung",
    CityID: "B",
    Version: "21.08.1",
  },
  // {
  //   CountyID: "C",
  //   CountyName: "基隆市",
  //   CountyCode: "10017",
  //   County: "Keelung",
  //   CityID: "C",
  //   Version: "21.08.1",
  // },
  {
    CountyID: "D",
    CountyName: "臺南市",
    CountyCode: "67000",
    County: "Tainan",
    CityID: "D",
    Version: "21.08.1",
  },
  // {
  //   CountyID: "E",
  //   CountyName: "高雄市",
  //   CountyCode: "64000",
  //   County: "Kaohsiung",
  //   CityID: "E",
  //   Version: "21.08.1",
  // },
  {
    CountyID: "F",
    CountyName: "新北市",
    CountyCode: "65000",
    County: "NewTaipei",
    CityID: "F",
    Version: "21.08.1",
  },
  // {
  //   CountyID: "G",
  //   CountyName: "宜蘭縣",
  //   CountyCode: "10002",
  //   County: "YilanCounty",
  //   CityID: "G",
  //   Version: "21.08.1",
  // },
  {
    CountyID: "H",
    CountyName: "桃園市",
    CountyCode: "68000",
    County: "Taoyuan",
    CityID: "H",
    Version: "21.08.1",
  },
  // {
  //   CountyID: "I",
  //   CountyName: "嘉義市",
  //   CountyCode: "10020",
  //   County: "Chiayi",
  //   CityID: "I",
  //   Version: "21.08.1",
  // },
  // {
  //   CountyID: "J",
  //   CountyName: "新竹縣",
  //   CountyCode: "10004",
  //   County: "HsinchuCounty",
  //   CityID: "J",
  //   Version: "21.08.1",
  // },
  // {
  //   CountyID: "K",
  //   CountyName: "苗栗縣",
  //   CountyCode: "10005",
  //   County: "MiaoliCounty",
  //   CityID: "K",
  //   Version: "21.08.1",
  // },
  // {
  //   CountyID: "M",
  //   CountyName: "南投縣",
  //   CountyCode: "10008",
  //   County: "NantouCounty",
  //   CityID: "M",
  //   Version: "21.08.1",
  // },
  // {
  //   CountyID: "N",
  //   CountyName: "彰化縣",
  //   CountyCode: "10007",
  //   County: "ChanghuaCounty",
  //   CityID: "N",
  //   Version: "21.08.1",
  // },
  // {
  //   CountyID: "O",
  //   CountyName: "新竹市",
  //   CountyCode: "10018",
  //   County: "Hsinchu",
  //   CityID: "O",
  //   Version: "21.08.1",
  // },
  // {
  //   CountyID: "P",
  //   CountyName: "雲林縣",
  //   CountyCode: "10009",
  //   County: "YunlinCounty",
  //   CityID: "P",
  //   Version: "21.08.1",
  // },
  // {
  //   CountyID: "Q",
  //   CountyName: "嘉義縣",
  //   CountyCode: "10010",
  //   County: "ChiayiCounty",
  //   CityID: "Q",
  //   Version: "21.08.1",
  // },
  // {
  //   CountyID: "T",
  //   CountyName: "屏東縣",
  //   CountyCode: "10013",
  //   County: "PingtungCounty",
  //   CityID: "T",
  //   Version: "21.08.1",
  // },
  // {
  //   CountyID: "U",
  //   CountyName: "花蓮縣",
  //   CountyCode: "10015",
  //   County: "HualienCounty",
  //   CityID: "U",
  //   Version: "21.08.1",
  // },
  // {
  //   CountyID: "V",
  //   CountyName: "臺東縣",
  //   CountyCode: "10014",
  //   County: "TaitungCounty",
  //   CityID: "V",
  //   Version: "21.08.1",
  // },
  // {
  //   CountyID: "W",
  //   CountyName: "金門縣",
  //   CountyCode: "09020",
  //   County: "KinmenCounty",
  //   CityID: "W",
  //   Version: "21.08.1",
  // },
  // {
  //   CountyID: "X",
  //   CountyName: "澎湖縣",
  //   CountyCode: "10016",
  //   County: "PenghuCounty",
  //   CityID: "X",
  //   Version: "21.08.1",
  // },
  // {
  //   CountyID: "Z",
  //   CountyName: "連江縣",
  //   CountyCode: "09007",
  //   County: "LienchiangCounty",
  //   CityID: "Z",
  //   Version: "21.08.1",
  // },
];

export default county;
